export const PHONE = "076 4949837";
export const PHONE_HREF = "tel:0764949837";
export const EMAIL = "thanhvinh6701@gmail.com";
export const ADDRESS = "507C Võ Nguyễn Giáp, An Khánh, Thủ Đức, TP.HCM";
export const ZALO_URL = "https://zalo.me/0764949837";
export const SITE_URL = "https://volkswagensaigon.vn";

export const BASE_IMG = "https://volkswagenthaodien.vn/wp-content/uploads";

export type Car = {
  id: string;
  name: string;
  price: string;
  originalPrice?: string;
  image: string;
  gallery: string[];
  badge: string | null;
  href: string;
  tagline: string;
  desc: string;
  specs: { label: string; value: string }[];
  features: string[];
};

export const cars: Car[] = [
  {
    id: "volkswagen-viloran-luxury",
    name: "Volkswagen Viloran Luxury",
    price: "2.288.000.000 ₫",
    image: `${BASE_IMG}/2024/11/xe-volkswagen-viloran-3.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/xe-volkswagen-viloran-3.webp`,
      `${BASE_IMG}/2024/11/viloran-2.webp`,
      `${BASE_IMG}/2024/11/viloran-4.webp`,
      `${BASE_IMG}/2024/11/Volkswagen-Viloran-Luxury-21.webp`,
      `${BASE_IMG}/2024/11/Volkswagen-Viloran-Luxury-18.webp`,
    ],
    badge: null,
    href: "/xe/volkswagen-viloran-luxury",
    tagline: "MPV hạng sang dành cho gia đình hiện đại",
    desc: "Volkswagen Viloran Luxury 2025 là mẫu MPV 7 chỗ cao cấp với không gian nội thất rộng rãi, thiết kế sang trọng và trang bị công nghệ tiên tiến. Viloran mang đến sự thoải mái tuyệt đối cho mọi thành viên trong gia đình.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "220 mã lực" },
      { label: "Mô-men xoắn", value: "350 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "Cầu trước (FWD)" },
      { label: "Số chỗ ngồi", value: "7 chỗ" },
      { label: "Chiều dài cơ sở", value: "3.180 mm" },
      { label: "Kích thước (D×R×C)", value: "5.175 × 1.909 × 1.755 mm" },
      { label: "Dung tích bình xăng", value: "70 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "8.5L/100km" },
    ],
    features: [
      "Màn hình cảm ứng 10 inch",
      "Điều hòa 3 vùng độc lập",
      "Ghế da chỉnh điện 8 hướng + sưởi + làm mát",
      "Cửa trượt điện 2 bên",
      "Camera 360°",
      "6 túi khí an toàn",
      "Hệ thống âm thanh 8 loa",
      "Đèn LED toàn phần",
      "Cốp điện tự động",
      "Kết nối Apple CarPlay / Android Auto",
    ],
  },
  {
    id: "volkswagen-viloran-premium",
    name: "Volkswagen Viloran Premium",
    price: "2.088.000.000 ₫",
    image: `${BASE_IMG}/2024/11/xe-volkswagen-viloran-3.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/xe-volkswagen-viloran-3.webp`,
      `${BASE_IMG}/2024/11/viloran-2.webp`,
      `${BASE_IMG}/2024/11/Volkswagen-Viloran-Luxury-17.webp`,
      `${BASE_IMG}/2024/11/Volkswagen-Viloran-Luxury-22.webp`,
    ],
    badge: null,
    href: "/xe/volkswagen-viloran-premium",
    tagline: "Không gian sang trọng, giá trị vượt trội",
    desc: "Volkswagen Viloran Premium 2025 mang đến trải nghiệm di chuyển cao cấp với đầy đủ tiện nghi hiện đại, phù hợp cho những gia đình tìm kiếm một chiếc MPV 7 chỗ chất lượng với mức giá hợp lý hơn bản Luxury.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "220 mã lực" },
      { label: "Mô-men xoắn", value: "350 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "Cầu trước (FWD)" },
      { label: "Số chỗ ngồi", value: "7 chỗ" },
      { label: "Chiều dài cơ sở", value: "3.180 mm" },
      { label: "Kích thước (D×R×C)", value: "5.175 × 1.909 × 1.755 mm" },
      { label: "Dung tích bình xăng", value: "70 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "8.5L/100km" },
    ],
    features: [
      "Màn hình cảm ứng 10 inch",
      "Điều hòa 3 vùng độc lập",
      "Ghế da chỉnh điện",
      "Cửa trượt điện 2 bên",
      "Camera lùi",
      "6 túi khí an toàn",
      "Đèn LED toàn phần",
      "Kết nối Apple CarPlay / Android Auto",
      "Cảm biến đỗ xe trước sau",
    ],
  },
  {
    id: "volkswagen-teramont",
    name: "Volkswagen Teramont",
    price: "1.998.000.000 ₫",
    originalPrice: "2.499.000.000 ₫",
    image: `${BASE_IMG}/2024/11/Teramont.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/Teramont.webp`,
      `${BASE_IMG}/2024/11/Teramont-4.webp`,
      `${BASE_IMG}/2024/11/Teramont-5.webp`,
      `${BASE_IMG}/2024/11/Teramont-6.webp`,
      `${BASE_IMG}/2024/11/Teramont-7.webp`,
    ],
    badge: "Ưu đãi",
    href: "/xe/volkswagen-teramont",
    tagline: "SUV 7 chỗ mạnh mẽ, đa địa hình",
    desc: "Volkswagen Teramont 2025 là mẫu SUV 7 chỗ hạng E lớn nhất của Volkswagen tại Việt Nam. Với động cơ TSI mạnh mẽ, hệ dẫn động 4Motion toàn thời gian và không gian nội thất rộng rãi, Teramont là lựa chọn lý tưởng cho gia đình năng động.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "220 mã lực" },
      { label: "Mô-men xoắn", value: "350 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "4Motion AWD toàn thời gian" },
      { label: "Số chỗ ngồi", value: "7 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.980 mm" },
      { label: "Kích thước (D×R×C)", value: "5.035 × 1.989 × 1.769 mm" },
      { label: "Dung tích bình xăng", value: "70 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "9.2L/100km" },
    ],
    features: [
      "Màn hình cảm ứng 12 inch",
      "Điều hòa 3 vùng độc lập",
      "Ghế da chỉnh điện + sưởi hàng 1-2",
      "Camera 360°",
      "10 túi khí an toàn",
      "Mâm hợp kim 20 inch",
      "Đèn LED matrix IQ.LIGHT",
      "Cốp điện tự động",
      "Hệ thống âm thanh Harman Kardon",
      "Kết nối Apple CarPlay / Android Auto",
      "Phanh tay điện tử",
      "Cruise Control thích ứng",
    ],
  },
  {
    id: "volkswagen-teramont-limited",
    name: "Volkswagen Teramont Limited",
    price: "2.138.000.000 ₫",
    originalPrice: "2.499.000.000 ₫",
    image: `${BASE_IMG}/2024/11/Teramont.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/Teramont.webp`,
      `${BASE_IMG}/2024/11/Teramont-8.webp`,
      `${BASE_IMG}/2024/11/Teramont-9.webp`,
      `${BASE_IMG}/2024/11/Teramont-10.webp`,
    ],
    badge: "Ưu đãi",
    href: "/xe/volkswagen-teramont-limited",
    tagline: "Phiên bản giới hạn, trang bị toàn diện",
    desc: "Volkswagen Teramont Limited 2025 là phiên bản đặc biệt với nhiều trang bị bổ sung cao cấp hơn so với bản tiêu chuẩn, mang đến trải nghiệm lái xe sang trọng và an toàn vượt trội.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "220 mã lực" },
      { label: "Mô-men xoắn", value: "350 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "4Motion AWD toàn thời gian" },
      { label: "Số chỗ ngồi", value: "7 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.980 mm" },
      { label: "Kích thước (D×R×C)", value: "5.035 × 1.989 × 1.769 mm" },
      { label: "Dung tích bình xăng", value: "70 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "9.2L/100km" },
    ],
    features: [
      "Tất cả tính năng bản Teramont tiêu chuẩn",
      "Ghế hàng 2 chỉnh điện riêng lẻ",
      "Màn hình sau hàng 2",
      "Mâm hợp kim đặc biệt phiên bản Limited",
      "Nội thất da Nappa cao cấp",
      "Hệ thống lọc không khí 3 tầng",
      "Sạc điện thoại không dây",
    ],
  },
  {
    id: "volkswagen-teramont-president",
    name: "Volkswagen Teramont President",
    price: "2.399.000.000 ₫",
    image: `${BASE_IMG}/2024/11/Teramont.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/Teramont.webp`,
      `${BASE_IMG}/2024/11/Teramont-11.webp`,
      `${BASE_IMG}/2024/11/Teramont-4.webp`,
      `${BASE_IMG}/2024/11/Teramont-5.webp`,
    ],
    badge: null,
    href: "/xe/volkswagen-teramont-president",
    tagline: "Đỉnh cao của dòng Teramont 7 chỗ",
    desc: "Volkswagen Teramont President 2025 là phiên bản cao cấp nhất của dòng Teramont, được trang bị đầy đủ mọi công nghệ và tiện nghi sang trọng nhất từ Volkswagen dành cho những ai không chấp nhận sự thỏa hiệp.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "220 mã lực" },
      { label: "Mô-men xoắn", value: "350 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "4Motion AWD toàn thời gian" },
      { label: "Số chỗ ngồi", value: "7 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.980 mm" },
      { label: "Kích thước (D×R×C)", value: "5.035 × 1.989 × 1.769 mm" },
      { label: "Dung tích bình xăng", value: "70 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "9.2L/100km" },
    ],
    features: [
      "Full option – trang bị cao nhất phân khúc",
      "Đèn LED matrix IQ.LIGHT tự động",
      "Nội thất da Nappa cao cấp",
      "Ghế hàng 1-2 chỉnh điện + massage",
      "Màn hình cảm ứng 12 inch + HUD",
      "Âm thanh Harman Kardon 12 loa",
      "10 túi khí",
      "Camera 360° HD",
      "Cửa sổ trời panoramic toàn cảnh",
      "Hệ thống treo khí nén tự động",
    ],
  },
  {
    id: "volkswagen-teramont-x-luxury",
    name: "Volkswagen Teramont X Luxury",
    price: "2.168.000.000 ₫",
    image: `${BASE_IMG}/2025/05/Betterimage.ai_1747730163872.webp`,
    gallery: [
      `${BASE_IMG}/2025/05/Betterimage.ai_1747730163872.webp`,
      `${BASE_IMG}/2024/11/Teramont.webp`,
      `${BASE_IMG}/2024/11/Teramont-6.webp`,
    ],
    badge: null,
    href: "/xe/volkswagen-teramont-x-luxury",
    tagline: "SUV 5 chỗ thể thao, hiện đại",
    desc: "Volkswagen Teramont X Luxury 2025 là phiên bản SUV 5 chỗ thể thao của dòng Teramont X, kết hợp hoàn hảo giữa thiết kế Coupe-SUV năng động và sự sang trọng đặc trưng của thương hiệu Volkswagen.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "220 mã lực" },
      { label: "Mô-men xoắn", value: "350 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "4Motion AWD toàn thời gian" },
      { label: "Số chỗ ngồi", value: "5 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.980 mm" },
      { label: "Dung tích cốp", value: "540 – 1.719 lít" },
      { label: "Dung tích bình xăng", value: "70 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "9.0L/100km" },
    ],
    features: [
      "Thiết kế Coupe-SUV thể thao",
      "Màn hình cảm ứng 12 inch",
      "Camera 360°",
      "Điều hòa 2 vùng tự động",
      "Ghế da chỉnh điện + sưởi",
      "Mâm hợp kim 20 inch",
      "Đèn LED matrix",
      "Kết nối Apple CarPlay / Android Auto",
      "Cốp điện tự động",
    ],
  },
  {
    id: "volkswagen-teramont-x-platinum",
    name: "Volkswagen Teramont X Platinum",
    price: "2.168.000.000 ₫",
    image: `${BASE_IMG}/2025/05/Betterimage.ai_1747730163872.webp`,
    gallery: [
      `${BASE_IMG}/2025/05/Betterimage.ai_1747730163872.webp`,
      `${BASE_IMG}/2024/11/Teramont.webp`,
      `${BASE_IMG}/2024/11/Teramont-7.webp`,
    ],
    badge: "Mới",
    href: "/xe/volkswagen-teramont-x-platinum",
    tagline: "Đỉnh cao Coupe-SUV 5 chỗ của Volkswagen",
    desc: "Volkswagen Teramont X Platinum 2025 là phiên bản cao cấp nhất của dòng Teramont X, được trang bị full option với mọi công nghệ tiên tiến nhất. Thiết kế Coupe-SUV độc đáo, mạnh mẽ và sang trọng.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "220 mã lực" },
      { label: "Mô-men xoắn", value: "350 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "4Motion AWD toàn thời gian" },
      { label: "Số chỗ ngồi", value: "5 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.980 mm" },
      { label: "Dung tích cốp", value: "540 – 1.719 lít" },
      { label: "Dung tích bình xăng", value: "70 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "9.0L/100km" },
    ],
    features: [
      "Full option – cao nhất dòng Teramont X",
      "Đèn LED matrix IQ.LIGHT tự động",
      "Nội thất da Nappa cao cấp",
      "Ghế chỉnh điện + massage hàng trước",
      "Màn hình 12 inch + HUD",
      "Âm thanh Harman Kardon",
      "Camera 360° HD",
      "Cửa sổ trời panoramic",
      "Sạc không dây Qi",
      "Cruise Control thích ứng",
    ],
  },
  {
    id: "volkswagen-tiguan-facelift",
    name: "Volkswagen Tiguan Facelift",
    price: "1.599.000.000 ₫",
    image: `${BASE_IMG}/2024/12/Tiguan-Facelift-1-1.webp`,
    gallery: [
      `${BASE_IMG}/2024/12/Tiguan-Facelift-1-1.webp`,
      `${BASE_IMG}/2024/12/Tiguan-Facelift-2.webp`,
      `${BASE_IMG}/2024/12/Tiguan-Facelift-3.webp`,
      `${BASE_IMG}/2024/12/Tiguan-Facelift-4.webp`,
      `${BASE_IMG}/2024/12/Tiguan-Facelift-5.webp`,
    ],
    badge: null,
    href: "/xe/volkswagen-tiguan-facelift",
    tagline: "Diện mạo mới, công nghệ tiên tiến",
    desc: "Volkswagen Tiguan Facelift 2025 mang đến diện mạo hoàn toàn mới với nhiều nâng cấp toàn diện về thiết kế và công nghệ. Động cơ eTSI tiết kiệm nhiên liệu, trang bị an toàn đầy đủ và không gian nội thất thực dụng.",
    specs: [
      { label: "Động cơ", value: "1.5L eTSI mild-hybrid" },
      { label: "Công suất", value: "150 mã lực" },
      { label: "Mô-men xoắn", value: "250 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "Cầu trước (FWD)" },
      { label: "Số chỗ ngồi", value: "5 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.686 mm" },
      { label: "Kích thước (D×R×C)", value: "4.537 × 1.842 × 1.658 mm" },
      { label: "Dung tích bình xăng", value: "60 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "7.1L/100km" },
    ],
    features: [
      "Động cơ mild-hybrid tiết kiệm nhiên liệu",
      "Màn hình cảm ứng 10 inch",
      "Điều hòa tự động 2 vùng",
      "Ghế da chỉnh điện hàng trước",
      "Camera lùi",
      "6 túi khí an toàn",
      "Đèn LED toàn phần",
      "Kết nối Apple CarPlay / Android Auto",
      "Cảm biến đỗ xe trước sau",
      "Phanh tay điện tử",
    ],
  },
  {
    id: "volkswagen-tiguan-platinum",
    name: "Volkswagen Tiguan Platinum",
    price: "1.688.000.000 ₫",
    image: `${BASE_IMG}/2024/11/Volkswagen-Tiguan-Platinum.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/Volkswagen-Tiguan-Platinum.webp`,
      `${BASE_IMG}/2024/12/Tiguan-Facelift-1-1.webp`,
      `${BASE_IMG}/2024/12/Tiguan-Facelift-7.webp`,
      `${BASE_IMG}/2024/12/Tiguan-Facelift-8.webp`,
    ],
    badge: null,
    href: "/xe/volkswagen-tiguan-platinum",
    tagline: "Phiên bản cao cấp nhất của Tiguan",
    desc: "Volkswagen Tiguan Platinum 2025 là phiên bản cao cấp nhất của dòng Tiguan, mang đến sự kết hợp hoàn hảo giữa thiết kế sang trọng, công nghệ hiện đại và hiệu suất vận hành mạnh mẽ. Đây là SUV compact hoàn hảo cho những ai yêu cầu cao nhất.",
    specs: [
      { label: "Động cơ", value: "2.0L TSI Turbo" },
      { label: "Công suất", value: "190 mã lực" },
      { label: "Mô-men xoắn", value: "320 Nm" },
      { label: "Hộp số", value: "7 cấp DSG ly hợp kép" },
      { label: "Dẫn động", value: "4Motion AWD" },
      { label: "Số chỗ ngồi", value: "5 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.686 mm" },
      { label: "Kích thước (D×R×C)", value: "4.537 × 1.842 × 1.658 mm" },
      { label: "Dung tích bình xăng", value: "60 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "8.0L/100km" },
    ],
    features: [
      "Dẫn động 4Motion AWD thông minh",
      "Màn hình cảm ứng 10 inch",
      "Điều hòa tự động 3 vùng",
      "Ghế da Nappa chỉnh điện + sưởi",
      "Camera 360°",
      "6 túi khí an toàn",
      "Mâm hợp kim 19 inch",
      "Đèn LED matrix tự động",
      "Cửa sổ trời panoramic",
      "Âm thanh Harman Kardon 9 loa",
      "Kết nối Apple CarPlay / Android Auto",
      "Cruise Control thích ứng",
    ],
  },
  {
    id: "volkswagen-touareg-elegance",
    name: "Volkswagen Touareg Elegance",
    price: "2.699.000.000 ₫",
    originalPrice: "2.999.000.000 ₫",
    image: `${BASE_IMG}/2024/11/Volkswagen-Touareg-Elegance.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/Volkswagen-Touareg-Elegance.webp`,
      `${BASE_IMG}/2024/11/Volkswagen-Touareg-Luxury.webp`,
    ],
    badge: "Ưu đãi",
    href: "/xe/volkswagen-touareg-elegance",
    tagline: "SUV hạng sang đẳng cấp châu Âu",
    desc: "Volkswagen Touareg Elegance 2026 là mẫu SUV hạng sang đại diện cho đỉnh cao của thương hiệu Volkswagen. Với động cơ V6 TDI mạnh mẽ, hệ thống treo khí nén và nội thất siêu cao cấp, Touareg mang đến trải nghiệm lái xe không thể nào quên.",
    specs: [
      { label: "Động cơ", value: "3.0L TDI V6 Turbo Diesel" },
      { label: "Công suất", value: "286 mã lực" },
      { label: "Mô-men xoắn", value: "600 Nm" },
      { label: "Hộp số", value: "8 cấp Tiptronic tự động" },
      { label: "Dẫn động", value: "4Motion AWD thường trực" },
      { label: "Số chỗ ngồi", value: "5 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.894 mm" },
      { label: "Kích thước (D×R×C)", value: "4.879 × 1.984 × 1.702 mm" },
      { label: "Dung tích bình xăng", value: "75 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "7.5L/100km" },
    ],
    features: [
      "Động cơ V6 TDI mạnh mẽ",
      "Hệ thống treo khí nén Airmatic tự chỉnh",
      "Màn hình Innovision Cockpit 15 inch",
      "Đồng hồ kỹ thuật số 12 inch",
      "Nội thất da Nappa cao cấp",
      "Ghế massage 14 hướng hàng trước",
      "Điều hòa 4 vùng độc lập",
      "Camera 360° Night Vision",
      "Hệ thống âm thanh Dynaudio 14 loa",
      "Cửa sổ trời panoramic 2 tầng",
      "Head-Up Display (HUD)",
      "Massage ghế sau",
    ],
  },
  {
    id: "volkswagen-touareg-luxury",
    name: "Volkswagen Touareg Luxury",
    price: "2.999.000.000 ₫",
    image: `${BASE_IMG}/2024/11/Volkswagen-Touareg-Luxury.webp`,
    gallery: [
      `${BASE_IMG}/2024/11/Volkswagen-Touareg-Luxury.webp`,
      `${BASE_IMG}/2024/11/Volkswagen-Touareg-Elegance.webp`,
    ],
    badge: null,
    href: "/xe/volkswagen-touareg-luxury",
    tagline: "Đỉnh cao sang trọng – không giới hạn",
    desc: "Volkswagen Touareg Luxury 2026 là phiên bản cao cấp nhất trong dòng Touareg, được trang bị mọi công nghệ và tiện nghi sang trọng nhất. Đây là biểu tượng của sự thịnh vượng và đẳng cấp trong phân khúc SUV hạng sang.",
    specs: [
      { label: "Động cơ", value: "3.0L TDI V6 Turbo Diesel" },
      { label: "Công suất", value: "286 mã lực" },
      { label: "Mô-men xoắn", value: "600 Nm" },
      { label: "Hộp số", value: "8 cấp Tiptronic tự động" },
      { label: "Dẫn động", value: "4Motion AWD thường trực" },
      { label: "Số chỗ ngồi", value: "5 chỗ" },
      { label: "Chiều dài cơ sở", value: "2.894 mm" },
      { label: "Kích thước (D×R×C)", value: "4.879 × 1.984 × 1.702 mm" },
      { label: "Dung tích bình xăng", value: "75 lít" },
      { label: "Tiêu thụ nhiên liệu", value: "7.5L/100km" },
    ],
    features: [
      "Tất cả tính năng bản Elegance",
      "Ghế hàng sau chỉnh điện riêng lẻ + massage",
      "Màn hình hàng sau riêng biệt",
      "Hệ thống Night Vision phát hiện người & động vật",
      "Đèn LED matrix IQ.LIGHT tự động hoàn toàn",
      "Khóa cổng tay nắm điện ẩn",
      "Hệ thống treo khí nén cao cấp nhất",
      "Sạc không dây hàng sau",
      "Nước hoa nội thất tự động",
    ],
  },
];

export const benefits = [
  {
    icon: "🤝",
    title: "Tư vấn chuyên nghiệp",
    desc: "Đội ngũ tư vấn viên được đào tạo bài bản, hỗ trợ bạn chọn xe phù hợp nhất.",
  },
  {
    icon: "🚗",
    title: "Lái thử miễn phí",
    desc: "Trải nghiệm cảm giác lái xe Volkswagen hoàn toàn miễn phí tại showroom.",
  },
  {
    icon: "🏠",
    title: "Giao xe tận nhà",
    desc: "Dịch vụ giao xe tận nơi, tiết kiệm thời gian quý báu của bạn.",
  },
  {
    icon: "💳",
    title: "Hỗ trợ vay 85%",
    desc: "Thủ tục nhanh gọn, hỗ trợ vay vốn lên đến 85% giá trị xe với lãi suất ưu đãi.",
  },
];

export const reviews = [
  {
    name: "Nguyễn Văn An",
    rating: 5,
    comment:
      "Showroom rất chuyên nghiệp, nhân viên tư vấn nhiệt tình. Tôi đã mua Tiguan Platinum và rất hài lòng với trải nghiệm mua xe tại đây.",
    car: "Tiguan Platinum",
  },
  {
    name: "Trần Thị Bích",
    rating: 5,
    comment:
      "Dịch vụ tuyệt vời! Được lái thử miễn phí, thủ tục vay vốn nhanh chóng. Nhân viên hỗ trợ tận tâm từ đầu đến cuối.",
    car: "Teramont 2025",
  },
  {
    name: "Lê Minh Khoa",
    rating: 5,
    comment:
      "Mua xe Viloran tại đây, giá tốt và được giao xe tận nhà. Trải nghiệm mua xe thoải mái, không áp lực. Rất hài lòng!",
    car: "Viloran Luxury",
  },
];

export type NewsArticle = {
  id: string;
  title: string;
  date: string;
  excerpt: string;
  image: string;
  content: { type: "p" | "h2" | "h3" | "ul"; text?: string; items?: string[] }[];
};

export const news: NewsArticle[] = [
  {
    id: "volkswagen-tiguan-facelift-2025",
    title: "Volkswagen Tiguan Facelift 2025 – Nâng cấp toàn diện, giá hấp dẫn",
    date: "10/05/2025",
    excerpt:
      "Volkswagen Tiguan Facelift 2025 mang đến diện mạo mới với nhiều công nghệ hiện đại được nâng cấp đáng kể so với thế hệ trước.",
    image: `${BASE_IMG}/2024/12/Tiguan-Facelift-2.webp`,
    content: [
      { type: "p", text: "Volkswagen Tiguan Facelift 2025 chính thức ra mắt tại thị trường Việt Nam với hàng loạt nâng cấp đáng chú ý về thiết kế, công nghệ và hiệu suất vận hành. Đây là phiên bản được người yêu xe VW mong đợi nhất trong năm nay." },
      { type: "h2", text: "Thiết kế ngoại thất mới mẻ, hiện đại hơn" },
      { type: "p", text: "Tiguan Facelift 2025 được làm mới với lưới tản nhiệt phẳng theo xu hướng thiết kế IQ.LIGHT của Volkswagen, tích hợp dải đèn LED ban ngày liền mạch chạy xuyên suốt mặt đầu xe. Cụm đèn hậu cũng được thiết kế lại với hiệu ứng 3D ấn tượng hơn." },
      { type: "p", text: "Bộ mâm hợp kim mới 18 inch và 19 inch với nhiều tùy chọn phong cách giúp Tiguan 2025 trở nên thể thao và sang trọng hơn so với thế hệ tiền nhiệm." },
      { type: "h2", text: "Nội thất và công nghệ vượt trội" },
      { type: "p", text: "Bên trong khoang lái, Tiguan Facelift 2025 được trang bị màn hình cảm ứng trung tâm 12,9 inch thế hệ mới chạy hệ điều hành MIB4, hỗ trợ kết nối không dây với Apple CarPlay và Android Auto. Cụm đồng hồ kỹ thuật số Digital Cockpit Pro 10,25 inch hiển thị đầy đủ thông tin lái xe." },
      { type: "ul", items: [
        "Màn hình cảm ứng 12,9 inch MIB4",
        "Điều hòa 3 vùng Climatronic tự động",
        "Ghế lái chỉnh điện 12 hướng có sưởi và làm mát",
        "Hệ thống âm thanh Harman Kardon 12 loa",
        "Cốp điện với cảm biến chân",
        "Camera 360° độ phân giải cao",
      ]},
      { type: "h2", text: "Động cơ và vận hành" },
      { type: "p", text: "Tiguan Facelift 2025 tiếp tục sử dụng khối động cơ 2.0L TSI Turbo sản sinh 190 mã lực và 320 Nm mô-men xoắn, kết hợp hộp số ly hợp kép DSG 7 cấp. Hệ dẫn động 4Motion AWD thông minh phân phối lực kéo linh hoạt theo điều kiện mặt đường." },
      { type: "h2", text: "Giá bán và chính sách ưu đãi tại Volkswagen Sài Gòn" },
      { type: "p", text: "Volkswagen Tiguan Facelift 2025 được phân phối chính hãng tại Showroom Volkswagen Sài Gòn với mức giá cạnh tranh. Khách hàng đặt cọc trong tháng 5/2025 sẽ được hưởng gói ưu đãi đặc biệt bao gồm hỗ trợ lãi suất 0% trong 12 tháng đầu và tặng gói phụ kiện chính hãng trị giá đến 50 triệu đồng." },
      { type: "p", text: "Liên hệ hotline 076 4949837 hoặc đến trực tiếp showroom tại 507C Võ Nguyễn Giáp, An Khánh, Thủ Đức, TP.HCM để được tư vấn và lái thử miễn phí." },
    ],
  },
  {
    id: "teramont-x-platinum-suv-cao-cap",
    title: "Teramont X Platinum – SUV 5 chỗ cao cấp nhất của VW tại Việt Nam",
    date: "05/05/2025",
    excerpt:
      "Volkswagen Teramont X Platinum 2025 là đỉnh cao của dòng Teramont X với trang bị full option, động cơ mạnh mẽ và công nghệ vượt trội.",
    image: `${BASE_IMG}/2025/05/Betterimage.ai_1747730163872.webp`,
    content: [
      { type: "p", text: "Volkswagen Teramont X Platinum 2025 vừa chính thức gia nhập thị trường Việt Nam, đánh dấu cột mốc quan trọng trong phân khúc SUV 5 chỗ hạng sang. Với thiết kế Coupe-SUV độc đáo và trang bị full option, Teramont X Platinum khẳng định vị thế đỉnh cao của thương hiệu VW tại Việt Nam." },
      { type: "h2", text: "Thiết kế Coupe-SUV nổi bật" },
      { type: "p", text: "Teramont X Platinum gây ấn tượng mạnh với đường nóc vát dốc đặc trưng kiểu Coupe-SUV, kết hợp cùng kích thước SUV cỡ lớn. Mặt đầu xe được thiết kế lại hoàn toàn với lưới tản nhiệt IQ.LIGHT rộng bản, tích hợp dải đèn LED ban ngày chạy xuyên suốt tạo điểm nhấn thị giác mạnh mẽ." },
      { type: "p", text: "Cụm đèn pha Matrix LED tự động điều chỉnh chùm sáng thông minh theo tình huống giao thông, vừa đảm bảo an toàn tối đa vừa không làm chói mắt các phương tiện đi ngược chiều." },
      { type: "h2", text: "Khoang nội thất đẳng cấp hạng sang" },
      { type: "ul", items: [
        "Màn hình cảm ứng trung tâm 15 inch MIB4 thế hệ mới",
        "Ghế da Nappa cao cấp chỉnh điện 14 hướng cho hàng ghế trước",
        "Hệ thống âm thanh Dynaudio Premium 14 loa",
        "Điều hòa 3 vùng độc lập với chế độ làm sạch không khí",
        "Panoramic Sunroof cửa sổ trời toàn cảnh 2 lớp",
        "Hệ thống đỗ xe tự động Park Assist Pro",
        "Head-up Display hiển thị thông tin trên kính lái",
      ]},
      { type: "h2", text: "Sức mạnh động cơ và công nghệ an toàn" },
      { type: "p", text: "Teramont X Platinum được trang bị khối động cơ 2.0L TSI 4 xi-lanh tăng áp, cho công suất tối đa 220 mã lực và mô-men xoắn 350 Nm. Kết hợp với hộp số tự động DSG 7 cấp và hệ dẫn động 4Motion AWD, xe có thể tăng tốc từ 0-100km/h chỉ trong 7,5 giây." },
      { type: "p", text: "Hệ thống IQ.DRIVE tích hợp đầy đủ các tính năng hỗ trợ lái tiên tiến: kiểm soát hành trình thích ứng ACC, cảnh báo va chạm phía trước với phanh khẩn cấp tự động, hỗ trợ giữ làn đường, cảnh báo điểm mù và hỗ trợ đỗ xe tự động." },
      { type: "h2", text: "Trải nghiệm lái thử tại Volkswagen Sài Gòn" },
      { type: "p", text: "Showroom Volkswagen Sài Gòn hiện đang trưng bày xe Teramont X Platinum 2025 và nhận lịch lái thử miễn phí. Đội ngũ tư vấn chuyên nghiệp sẽ hỗ trợ bạn tìm hiểu chi tiết về xe và các gói tài chính hấp dẫn với lãi suất ưu đãi, hỗ trợ vay đến 85% giá trị xe." },
    ],
  },
  {
    id: "volkswagen-viloran-mpv-hang-sang",
    title: "Volkswagen Viloran – MPV hạng sang lý tưởng cho gia đình",
    date: "01/05/2025",
    excerpt:
      "Viloran 2025 tiếp tục khẳng định vị thế MPV cao cấp với nội thất sang trọng, không gian rộng rãi và loạt công nghệ tiên tiến.",
    image: `${BASE_IMG}/2024/11/Volkswagen-Viloran-Luxury-21.webp`,
    content: [
      { type: "p", text: "Volkswagen Viloran 2025 tiếp tục là lựa chọn hàng đầu trong phân khúc MPV 7 chỗ cao cấp tại Việt Nam. Với triết lý thiết kế lấy người dùng làm trung tâm, Viloran mang đến trải nghiệm di chuyển sang trọng và thoải mái nhất cho mọi thành viên trong gia đình." },
      { type: "h2", text: "Không gian nội thất rộng rãi, đẳng cấp" },
      { type: "p", text: "Viloran 2025 gây ấn tượng ngay từ cái nhìn đầu tiên với khoang nội thất rộng rãi bậc nhất phân khúc. Chiều dài cơ sở 3.180 mm đảm bảo không gian để chân thoải mái cho cả 7 hành khách, đặc biệt là hàng ghế thứ 2 với kiểu ghế thương gia (Captain Seats) có thể ngả tựa và kéo dài." },
      { type: "ul", items: [
        "Ghế hàng 2 kiểu thương gia chỉnh điện 8 hướng",
        "Cửa trượt điện 2 bên với cảm biến chướng ngại vật",
        "Màn hình giải trí hàng ghế sau 10 inch",
        "Hệ thống điều hòa 3 vùng độc lập",
        "Bàn làm việc gấp tích hợp tại hàng ghế giữa",
        "Sàn xe phẳng thoáng không có cầu truyền động",
      ]},
      { type: "h2", text: "Công nghệ hiện đại, an toàn thông minh" },
      { type: "p", text: "Viloran 2025 được trang bị màn hình cảm ứng trung tâm 10 inch, hệ thống âm thanh 8 loa chất lượng cao và kết nối không dây với Apple CarPlay / Android Auto. Hệ thống camera 360° độ phân giải cao hỗ trợ quan sát toàn cảnh xung quanh xe, giúp việc đỗ xe và di chuyển trong đô thị trở nên dễ dàng hơn." },
      { type: "p", text: "Về an toàn, Viloran được trang bị 6 túi khí, hệ thống phanh ABS + EBD + ESC, cảnh báo va chạm phía trước, hỗ trợ giữ làn đường và kiểm soát hành trình thích ứng. Tất cả nhằm bảo vệ tối đa cho các thành viên trong gia đình bạn." },
      { type: "h2", text: "Hai phiên bản phù hợp mọi nhu cầu" },
      { type: "p", text: "Volkswagen Viloran 2025 tại thị trường Việt Nam có 2 phiên bản: Viloran Premium (2.088.000.000 ₫) và Viloran Luxury (2.288.000.000 ₫). Cả hai đều được nhập khẩu nguyên chiếc, bảo hành chính hãng 5 năm hoặc 150.000 km tùy điều kiện đến trước." },
      { type: "h2", text: "Đặt lịch lái thử ngay hôm nay" },
      { type: "p", text: "Showroom Volkswagen Sài Gòn tại 507C Võ Nguyễn Giáp, An Khánh, Thủ Đức, TP.HCM đang có xe trưng bày và nhận đặt cọc. Liên hệ hotline 076 4949837 để được tư vấn và sắp xếp lái thử miễn phí tận nơi." },
    ],
  },
];

export const navLinks = [
  { label: "Trang chủ", href: "/" },
  { label: "Các dòng xe", href: "/xe" },
  { label: "Đăng ký lái thử", href: "/#lai-thu" },
  { label: "Bảng giá", href: "/xe" },
  { label: "Dịch vụ", href: "/#dich-vu" },
  { label: "Tin tức", href: "/#tin-tuc" },
  { label: "Liên hệ", href: "/#footer" },
];
